version: '3.8'

networks:
  corp:
    driver: bridge

services:
  client:
    container_name: client
    build:
      context: ./
      cache_from:
        - nx-dropteam:nx-base
      dockerfile: ./apps/client/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: client:nx-dev
    ports:
      - 4200:4200
    environment:
      NODE_ENV: 'development'
      PORT: 4200
    networks:
      - corp
    restart: on-failure
